-- Bridge to the nix-wrapper-modules "info plugin" generated by neovim.nix.
--
-- When neovim is built by nix, `config.info` is exposed as a lua module whose
-- name lives in `vim.g.nix_info_plugin_name` (default "nix-info"). We read the
-- enable-state of each language/group/tool from it to gate the tool registries
-- (LSP servers, formatters, linters) that actually *invoke* a binary.
--
-- Everything here is a protected call: if this config is run OUTSIDE nix (e.g. a
-- live-editable `stdpath('config')` checkout), the info plugin simply does not
-- exist. In that case every query falls back to `true` (enabled), so the config
-- behaves exactly as it did before this bridge existed — nothing is gated off.

local M = {}

-- Resolve the info plugin once. `ok` is false when running without nix.
local ok, info = false, nil
local name = vim.g.nix_info_plugin_name
if name then
	ok, info = pcall(require, name)
end

-- Whether the nix bridge is present at all. Useful for callers that want to
-- keep the full (ungated) set when running impurely.
M.available = ok and type(info) == "table"

-- enabled(kind, key) -> boolean
--   kind: "languages" | "groups" | "tools"
--   key:  e.g. "rust", "web", "extras"
-- Returns true when nix has the toggle on, OR when we are not running under nix
-- (default-open, so an impure checkout loses no functionality).
function M.enabled(kind, key)
	if not M.available then
		return true
	end
	-- Index directly rather than via the info plugin's `__call` helper: that
	-- helper does `(tbl ~= nil) and tbl or default`, which collapses a genuine
	-- `false` to the default — so it can never report a disabled toggle. We walk
	-- the table ourselves and treat missing keys as enabled (default-open).
	local root = info.info
	if type(root) ~= "table" then
		return true
	end
	local bucket = root[kind]
	if type(bucket) ~= "table" then
		return true
	end
	-- Only an explicit `false` disables; nil/absent stays enabled.
	return bucket[key] ~= false
end

-- Convenience wrappers.
function M.language(key)
	return M.enabled("languages", key)
end
function M.tool(key)
	return M.enabled("tools", key)
end
function M.group(key)
	return M.enabled("groups", key)
end

-- collect(spec) flattens a { languages=?, groups=?, tools=?, always=? } spec
-- into a single deduplicated list, keeping only entries whose toggle is enabled.
--
--   nix.collect({
--     languages = { python = { "ruff", "pyrefly" }, nix = { "nixd", "nil_ls" } },
--     tools     = { extras = { "ast_grep" } },
--     always    = { "awk_ls" },  -- no toggle; always kept
--   })
--
-- `always` entries are never gated. Every other key is a toggle name under its
-- kind; its list is included only when that toggle is enabled (or when running
-- without nix, where everything is enabled).
--
-- OR semantics for shared tools: a server/tool used by several languages (e.g.
-- tailwindcss for html+css, ltex for markdown+latex) can be listed under every
-- relevant key. It is kept when ANY of those toggles is on, and the dedup below
-- ensures it is only emitted once. First-seen order is preserved.
function M.collect(spec)
	local out, seen = {}, {}
	local function add(items)
		for _, item in ipairs(items) do
			if not seen[item] then
				seen[item] = true
				table.insert(out, item)
			end
		end
	end
	add(spec.always or {})
	for _, kind in ipairs({ "languages", "groups", "tools" }) do
		for key, items in pairs(spec[kind] or {}) do
			if M.enabled(kind, key) then
				add(items)
			end
		end
	end
	return out
end

return M
