local bufnr = vim.api.nvim_get_current_buf()
local key_prefix = "<leader>u"

local rust_keymap = function(lhs, rhs, desc)
	vim.keymap.set("n", key_prefix .. lhs, rhs, { silent = true, noremap = true, desc = desc, buffer = bufnr })
end

vim.keymap.set("n", "<F5>", "<esc>:w<bar>!cargo run<cr>", { silent = true, buffer = bufnr })
vim.keymap.set("n", "<F3>", "<esc>:w<bar>!cargo run --release<cr>", { silent = true, buffer = bufnr })
vim.keymap.set("n", "<F4>", "<esc>:w<bar>!maturin develop<cr>", { silent = true, buffer = bufnr })
vim.keymap.set("n", "<F6>", "<esc>:w<bar>!maturin develop --release<cr>", { silent = true, buffer = bufnr })
vim.keymap.set("n", "<F7>", "<esc>:w<bar>!cargo clippy<cr>", { silent = true, buffer = bufnr })
vim.keymap.set("n", "<F8>", "<esc>:w<bar>!cargo test<cr>", { silent = true, buffer = bufnr })
vim.keymap.set("n", "<F9>", "<esc>:w<bar>!cargo doc --no-deps --open<cr>", { silent = true, buffer = bufnr })

rust_keymap("a", function()
	vim.cmd.RustLsp("codeAction")
end, "Code actions")
rust_keymap("m", function()
	vim.cmd.RustLsp("expandMacro")
end, "Expand macro")
vim.keymap.set("n", "<CA-j>", function()
	vim.cmd.RustLsp("moveItem", "down")
end, { silent = true, buffer = bufnr, desc = "Rust move item down" })
vim.keymap.set("n", "<CA-k>", function()
	vim.cmd.RustLsp("moveItem", "up")
end, { silent = true, buffer = bufnr, desc = "Rust move item up" })
rust_keymap("h", function()
	vim.cmd.RustLsp("hover", "actions")
	vim.cmd.RustLsp("hover", "actions")
end, "Hover actions")
rust_keymap("e", function()
	vim.cmd.RustLsp("explainError")
end, "Explain error")
rust_keymap("d", function()
	vim.cmd.RustLsp("renderDiagnostic")
end, "Render diagnostic")
rust_keymap("c", function()
	vim.cmd.RustLsp("openCargo")
end, "Open Cargo.toml")

-- quickfix
QF_KEYMAP("c", ":make clippy<CR>", "Run cargo clippy")
QF_KEYMAP("C", ":make check<CR>", "Run cargo check")
QF_KEYMAP("t", ":make test<CR>", "Run cargo test")
vim.keymap.set("n", "<leader>x", ":make run<CR>", { desc = "Cargo run" })
vim.keymap.set("n", "<leader>X", ":make run --release<CR>", { desc = "Cargo run --release" })
